---
- hosts: all
  become: yes
  gather_facts: false
  tasks:
    - name: set banner
      lineinfile:
        path: /etc/ssh/sshd_config
        regex: '^#Banner none'
        line: 'Banner /etc/motd'
        state: present
    - name: X11Forwarding disabled
      lineinfile:
        path: /etc/ssh/sshd_config
       # regex: '^X11Forwarding yes'
        line: X11Forwarding no
        state: present
    - name: MaxAuthTries to 3 
      lineinfile:
        path: /etc/ssh/sshd_config
        regex: '^#MaxAuthTries 6'
        line: MaxAuthTries 3
