---
# tasks file for sample-mysql
- name: create partition
  parted: 
    device: /dev/sdb
    number: '1'
    state: present
    part_end: '800MiB'

- name: create vol group
  lvg:
    vg: vg_database 
    pvs: /dev/sdb1
- name: create logical vol
  lvol:
    vg: vg_database
    lv: lv_mysql
    size: 512m

- name: format to fs
  filesystem:
    dev: /dev/vg_database/lv_mysql
    fstype: xfs

- name: mount FS
  mount:
    state: mounted
    path: /mnt/mysql_backups
    fstype: xfs
    src: /dev/vg_database/lv_mysql

- name: install mysql
  yum: 
    name: mariadb
    state: latest
- name: make sure mysql is running and enabled
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - mariadb
    - firewalld

- name: allow firewall
  firewalld:
    port: 3306/tcp
    state: enabled
    permanent: yes
    immediate: yes

- name: change password of root
  mysql_user:
    name: root
    password: "{{ database_password }}"
    state: present

- name: add template
  template:
    dest: /etc/my.cnf
    src: my.cnf.j2
 
