---
- hosts: web_servers
  become: yes
  vars: 
    - apache_port: 80
    - webdir: /var/www/html
  serial:
    - 1
    - 25%
  tasks:
    - name: create temp directory for git
      tempfile:
        state: directory
        prefix: gitrepo_
      run_once: yes
      delegate_to: localhost
      register: tmpresult
    - name: get the path of tmp
      set_fact:
        localdir: "{{ tmpresult.path }}"
      run_once: yes

    - name: clone from git
      git:
        repo: https://github.com/stodomie289/webapp.git
        dest: "{{ localdir }}"
      delegate_to: localhost
      run_once: yes

    - name: get the local files
      set_fact:
        localdir_files: "{{ query('fileglob', localdir + '/*') | map('relpath', localdir) | list }}"
      delegate_to: localhost

    - name: local files
      debug: 
        msg: "{{ localdir_files }}"

    - name: get remote files
      find:
        path: "{{ webdir }}"
      register: findresult

    - name: get all remote files
      set_fact:
         remotedir_files: "{{ findresult.files | map(attribute='path') | map('relpath', webdir) | list }}"
    - name: get all remote files
      debug:
        msg: "{{ remotedir_files }}"

    - name: whitelist files
      file:
        state: absent
        path: "{{ webdir }}/{{ item }}"
      loop: "{{ remotedir_files | difference(localdir_files) }}"

    - name: copy files
      copy:
        src: "{{ localdir }}/{{ item }}"
        dest: "{{ webdir }}"
      loop: "{{ localdir_files }}"
