---
- hosts: web_servers
  become: yes
  serial:
    - 1
    - 25%
  vars:
    - apache_port: 80
  pre_tasks:
    - name: disable backend server
      haproxy:
        backend: app
        host: "{{ inventory_hostname }}"
        state: disabled
      delegate_to: "{{ item }}"
      with_items: "{{ groups['lb_servers'] }}"

  roles:
    - role: webapp

  post_tasks:
   - name: smoke test
     uri:
       url: "http://{{ inventory_hostname }}:{{ apache_port }}"
       method: GET
       return_content: yes
     register: urires
     delegate_to: "{{ groups['lb_servers'][0] }}"
   - debug:
       var: urires
   - name: enable back
     haproxy: 
       backend: app
       host: "{{ inventory_hostname }}"
       state: enabled
     delegate_to: "{{ item }}"
     with_items: "{{ groups['lb_servers'] }}"
