---
- hosts: localhost
  tasks:
    - name: task1 gather default ip
      set_fact:
         mysqlIP: "{{ ansible_default_ipv4['address'] }}/{{ ansible_default_ipv4['netmask'] }}"
    - debug:
        msg: "{{ mysqlIP }}"
    - name: task 2
      debug:
        msg: "{{ mysqlIP | ipaddr('network/prefix') }}"
    - name: task 3
      debug:
        msg: "{{ mysqlIP | ipaddr('prefix') }}" 
    - name: task 4
      debug: 
        msg: "{{ '192.168.56.2' | ipaddr('network/prefix') }}"
    - name: test if IP or network
      debug:
        msg: "{{ '192.168.0.3/24' | ipaddr('address') }}" 
    - name: test if ip 
      debug:
        msg: "{{ '192.168.0.2/255.255.255.0' | ipaddr('host/prefix') }}"
    - name: check network
      debug:
        msg: "{{ '192.168.0.12/24' | ipaddr('network') }}"
    - name: check network
      debug:
        msg: "{{ '192.168.0.0/24' | ipaddr('net') }}"
