---
- name: pre tasks
  hosts: web_servers
  serial:
     - 1
  pre_tasks:
     - debug:
         msg: "http://{{ inventory_hostname }}:80"
     - name: disable webserver
       haproxy:
         backend: app
         host: "{{ inventory_hostname }}"
         state: disabled
       delegate_to: load_balancer

- name: Deploy HAProxy
  import_playbook: deploy_haproxy.yml

- name: Deploy Web Server
  import_playbook: deploy_apache.yml

- name: Deploy Web App
  import_playbook: deploy_webapp.yml

- name: post tasks
  hosts: web_servers
  post_tasks:
     - debug:
         msg: "http://{{ inventory_hostname }}:80"
     - name: enabled back
       haproxy:
         backend: app
         host: "{{ inventory_hostname }}"
         state: enabled
       delegate_to: load_balancer
     - name: smoke pre test
       uri:
         url: "http://{{ inventory_hostname }}:80"
         return_content: yes
         method: GET
       register: result
       delegate_to: load_balancer
       ignore_errors: yes
