--- 
- hosts: localhost
  become: yes
  gather_facts: no
  vars:
    users:
       - ava
       - avery
  tasks:
    - name: create user
      user:
        name: "{{ item }}"
        state: present
      loop: "{{ users }}"
    - name: create authorized key
      authorized_key:
        user: "{{ item }}"
        key: "{{ lookup('file', item+ '/id_rsa.pub') }}"
        state: present
      loop: "{{ users }}"

