---
- name: block execution
  hosts: all
  tasks:
    - name: run block when ansible Distro is CentOS
      block:
        - name: install given packages
          yum:
            name:
              - httpd
            state: present
        - name: enable and start httpd
          systemd:
            name: httpd
            state: restarted
            enabled: yes
        - name: add firewall
          firewalld:
            port: 80/tcp
            state: enabled
            immediate: yes
            permanent: yes
      become: yes
      when: ansible_distribution == 'CentOS'
      # ignore_errors: yes
      rescue:
        - name: after block
          debug:
            msg: "Eric Sto DOmingo RHCA"
      always:
        - name: 
          debug:
            msg: "Eric STo DOmingo, CCNA CCNP RHCE RHCA"      
