---
- hosts: web_servers
  become: yes
  serial:
    - 1
  vars:
    - apache_port: 80
  pre_tasks:
    - name: show what host is being disabled
      debug:
        msg: "{{ inventory_hostname }}"
    - name: disable backedn web in proxy
      haproxy:
        backend: app
        host: "{{ inventory_hostname }}"
        state: disabled
      delegate_to: "{{ item }}"
      with_items: "{{ groups['lb_servers'] }}"
  
  roles: 
    - role: webapp

  post_tasks:
    - name: smoke test 
      uri:
        url: "https://{{ inventory_hostname }}:{{ apache_port }}"
        return_content: yes
        method: GET
      register: uriresult
      delegate_to: "{{ groups['lb_servers'][0] }}"
    - name: check the result
      debug:
        var: uriresult

    - name: enable back
      haproxy: 
        backend: app
        host: "{{ inventory_hostname }}"
        state: enabled
      delegate_to: "{{ item }}"
      with_items: "{{ groups['lb_servers'] }}"


