---
- hosts: localhost
  gather_facts: no
  become: yes
  tasks:
    - name: read output of query lines
      debug:
        msg: "{{ query('lines', 'ls /grep', errors='warn') }}"
    - name: read output of lookup file
      debug:
        msg: "{{ lookup('file', 'myfile.txt', errors='warn') }}"
    - name: template the lookup
      copy:
        dest: /tmp/sample_list.txt
        content: "{{ lookup('template', 'server_list.j2') }}"
    - name: checking template
      debug:
        msg: "{{ lookup('template', 'server_list.j2') }}"
    - name: debug data
      debug: 
        msg: "{{ item[1] }}"
      loop:
        - "{{ query('lines', 'cat myfile.txt') }}"
        - "{{ query('lines', 'cat /etc/hosts') }}"
      tags: itemized
    - name: url lookup
      copy:
        content: "{{ lookup('url', 'http://192.168.0.13/#/login') }}"
        dest: /tmp/testlookup.txt
    - name: cat
      command: 'cat /tmp/testlookup.txt'
      register: cat
    - debug:
        var: cat 
    - name: uri
      uri:
        url: 'http://192.168.0.13/#/login'
        return_content: yes
        method: get
        status_code: 200
      register: uriresult
    - debug:
         var: uriresult
