---
- hosts: localhost
  become: yes
  tasks:
    - name: gather only network facts
      setup:
        gather_subset:
          - network
      register: network
    - name: check
      debug:
        var: network
