--- 
- hosts: database
  become: yes
  tasks:
    - name: database_lits created
      copy:
        dest: /mnt/mysql_backups/database_list.txt
        content: |
          dev,test,qa,prod
    - name: archive
      archive:
        path: /mnt/mysql_backups/database_list.txt
        dest: /mnt/mysql_backups/archive.gz
        format: gz
