---
- hosts: database
  become: yes
  tasks:
    - name: create folder
      file:
        state: directory
        path: /etc/ansible/facts.d
    - name: create custom file
      copy:
        dest: /etc/ansible/facts.d/custom.fact
        content: |
          [sample_exam]
          server_role=mysql
    - debug:
        msg: "{{ hostvars['server_role'] }}"
