---
- hosts: all   
  become: yes
  tasks:
     - name: proxy motd
       copy: 
         dest: /etc/motd.yml
         content: |
           “Welcome to HAProxy server”
       when: " inventory_hostname in groups['proxy']"
     - name: web motd
       copy:
         dest: /etc/motd
         content: |
           "Welcome to Apache server”
       when: " inventory_hostname in groups['webservers']"

     - name: db motd
       copy:
         dest: /etc/motd
         content: |
           “Welcome to MySQL server”
       when: "inventory_hostname in groups['database']"
