---
- hosts: all
  become: yes
  tasks:
    - name: install in proxy
      yum:
        name:
          - tcpdump
          - mailx
        state: latest
      when: inventory_hostname in groups['proxy']
    - name: install in database
      yum:
        name: 
          - lsof
          - mailx
        state: latest
      when: inventory_hostname in groups['database']

